export const authActions = {
  AUTH_REQUEST: "AUTH_REQUEST",
  AUTH_SUCCESS: "AUTH_SUCCESS",
  AUTH_FAILURE: "AUTH_FAILURE",

  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",

  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
};

export const noteActions = {
  FETCH_ALL_NOTES_REQUEST: "FETCH_ALL_NOTES_REQUEST",
  FETCH_ALL_NOTES_SUCCESS: "FETCH_ALL_NOTES_SUCCESS",
  FETCH_ALL_NOTES_FAILURE: "FETCH_ALL_NOTES_FAILURE",

  CREATE_NOTE: "CREATE_NOTE",
  UPDATE_NOTE: "UPDATE_NOTE",
  DELETE_NOTE: "DELETE_NOTE",
};

export const labelActions = {
  FETCH_ALL_LABELS_REQUEST: "FETCH_ALL_LABELS_REQUEST",
  FETCH_ALL_LABELS_SUCCESS: "FETCH_ALL_LABELS_SUCCESS",
  FETCH_ALL_LABELS_FAILURE: "FETCH_ALL_LABELS_FAILURE",

  CREATE_LABEL: "CREATE_LABEL",
  UPDATE_LABEL: "UPDATE_LABEL",
  DELETE_LABEL: "DELETE_LABEL",
};

// export const IS_LOADING = "IS_LOADING";
