export const authActions = {
  AUTHENTICATED: "AUTHENTICATED",
  NOT_AUTHENTICATED: "NOT_AUTHENTICATED",

  //   LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",

  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",

  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
};

export const noteActions = {
  FETCH_ALL_NOTES_REQUEST: "FETCH_ALL_NOTES_REQUEST",
  FETCH_ALL_NOTES_SUCCESS: "FETCH_ALL_NOTES_SUCCESS",
  FETCH_ALL_NOTES_FAILURE: "FETCH_ALL_NOTES_FAILURE",

  FETCH_ALL_NOTES: "FETCH_ALL_NOTES",
  CREATE_NOTE: "CREATE_NOTE",
  UPDATE_NOTE: "UPDATE_NOTE",
};

export const labelActions = {
  FETCH_ALL_LABELS_REQUEST: "FETCH_ALL_LABELS_REQUEST",
  FETCH_ALL_LABELS_SUCCESS: "FETCH_ALL_LABELS_SUCCESS",
  FETCH_ALL_LABELS_FAILURE: "FETCH_ALL_LABELS_FAILURE",

  FETCH_ALL_LABELS: "FETCH_ALL_LABELS",
  CREATE_LABEL: "CREATE_LABEL",
  UPDATE_LABEL: "UPDATE_LABEL",
};