export const FETCH_ALL_NOTES_REQUEST = "FETCH_ALL_NOTES_REQUEST";
export const FETCH_ALL_NOTES_SUCCESS = "FETCH_ALL_NOTES_SUCCESS";
export const FETCH_ALL_NOTES_FAILURE = "FETCH_ALL_NOTES_FAILURE";

export const FETCH_ALL_NOTES = "FETCH_ALL_NOTES";
export const CREATE_NOTE = "CREATE_NOTE";
export const UPDATE_NOTE = "UPDATE_NOTE";

export const FETCH_ALL_LABELS = "FETCH_ALL_LABELS";
export const CREATE_LABEL = "CREATE_LABEL";
export const UPDATE_LABEL = "UPDATE_LABEL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const AUTHENTICATED = "AUTH_SUCCESS";
export const NOT_AUTHENTICATED = "AUTH_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

// export const IS_LOADING = "IS_LOADING";
